### ISSUE TITLE
Large fq file, low read counts

### ISSUE THREAD

**Issue by mgosborn** [motu-tool/mOTUs#57]
Hi, I am testing a single sample from a larger dataset. For this sample I have two fastq files (paired end) with ~33 million reads. Average read length is ~145bp. When running mOTUs2, the output lists many species, most of which have relative abundance of 0. I tried running with a higher taxonomy level (phylum) and printed the actual read counts. I was surprised that only ~180 reads were mapping and that only 32 were left unmapped. Do you have any insight on why I'm getting such low numbers? 

This was my most recent command: motus profile -f forward.fq -r reverse.fq -c -t 8 -k phylum

Thank you!

**Comment by AlessioMilanese** [comment]
Hi @mgosborn ,
Thanks for your interest in mOTUs!

You have quite some reads and of good length, so lowering the filters (like `-g 1` and `-l 45`) will probably not improve the recall.
Which kind of samples are you analyzing? Are they from soil?

**Comment by mgosborn** [comment]
Hi Alessio, 

I'm working with marine organisms grown in filtered seawater. I'm not expecting all of the reads to map to bacteria, but when I ran the same sample through kraken2 about 7million reads identified as bacteria so I was expecting to see higher numbers with the mOTUs output.

**Comment by SuShiAtGit** [comment]
Hi there, 

If about 7 M reads are indeed of bacterial origin, we should expect mOTUs to map roughly 35k reads if the organisms are represented in the database at the species level. The result will also depend on the distribution of relative abundances. However, 180+32 seems low indeed, and could mean that the abundant taxa in your sample are indeed not represented at the species level. Note that mOTUs will summarise species level abundances to higher taxonomic ranks, so that setting the -k option to phylum will not increase sensitivity. For this reason, your data may be interesting in the sense that they would add missing taxa to the database. If you are familiar with MAG construction, you may be interested in using the feature to extend the database with custom data, which would enable you to profile your sample(s) at the species-level. If you do not require relative species-level abundances, you might also consider using MetaPhlan for your data, which uses clade-specific genes, so that you may get higher sensitivity at higher taxonomic ranks.

Hope this helps.

**Comment by mgosborn** [comment]
Thanks! I will look into MetaPhlan. The next step is MAG construction, but we were hoping to have a quicker assessment of taxonomy first. Could you explain your first sentence more ("If about 7 M reads are indeed of bacterial origin, we should expect mOTUs to map roughly 35k reads if the organisms are represented in the database at the species level.")? 

Why would we expect the number of mOTUs mapped reads be so much lower?

**Comment by mgosborn** [comment]
And another question- How are the unmapped (-1) reads counted? I would have thought that the millions (or thousands, if it needs to first recognize it as bacteria) of unmapped reads would have ended up here.

**Comment by AlessioMilanese** [comment]
Hi @mgosborn ,

> Why would we expect the number of mOTUs mapped reads be so much lower?

This comes from calculating the average number of reads that are expected to map to the 10 marker genes that we use in mTOUs. For mOTUs we use only the reads that map to these marker genes and not all reads. Hence, for profiling we use a small part of the reads.

> And another question- How are the unmapped (-1) reads counted? I would have thought that the millions (or thousands, if it needs to first recognize it as bacteria) of unmapped reads would have ended up here.

The -1 are sequences from the 10 marker genes that we didnt manage to link into species. Basically, we observed these genes in nature, but we didnt manage to link them to a species.

Now, I think you might have some completely new organisms that we never saw before (not even in this -1), and that is why there are so few reads mapped.

**Comment by MalbertR** [comment]
Hi @AlessioMilanese 

I am also having a similar issue. According to one of your previous responses, it seems like we should expect a mapping rate at about 0.5%, right? 
In my case, I'm only getting ~1.6k reads mapped from a 4m paired-end reads (so 8m reads in total) sample. It's a human gut (fecal) sample. 

Any words as to why you think the mapping rate is so low? Obviously pretty much any sample will contain genomes that are not present in your database, but I would have thought the human gut would be pretty well covered. 

Thanks.

**Comment by AlessioMilanese** [comment]
Hi @MalbertR 

I added more info to the FAQ ([link](https://github.com/motu-tool/mOTUs_v2/wiki/FAQ#3-how-many-motus-read-counts-should-i-expect-to-have)).

Given 8 million total read, what you observe for human fecal samples is correct.

> Any words as to why you think the mapping rate is so low? Obviously pretty much any sample will contain genomes that are not present in your database, but I would have thought the human gut would be pretty well covered.

The issue is not with the genomes missing from the database, rather on having really few reads that map to the marker genes that we use for profiling. I would suggest to use mOTUs for samples with at least 35m (total) reads. In the evaluations so far (and not only our internal evaluations), mOTUs has higher accuracy and recall compared to other k-mer based tools (like kraken, Centrifuge, etc.); but this is true if there are enough reads. You can try to use kraken for your analyses, you will find more species, but there will be many more false positives as well.

**Comment by MalbertR** [comment]
> Hi @MalbertR
> 
> I added more info to the FAQ ([link](https://github.com/motu-tool/mOTUs_v2/wiki/FAQ#3-how-many-motus-read-counts-should-i-expect-to-have)).
> 
> Given 8 million total read, what you observe for human fecal samples is correct.
> 
> > Any words as to why you think the mapping rate is so low? Obviously pretty much any sample will contain genomes that are not present in your database, but I would have thought the human gut would be pretty well covered.
> 
> The issue is not with the genomes missing from the database, rather on having really few reads that map to the marker genes that we use for profiling. I would suggest to use mOTUs for samples with at least 35m (total) reads. In the evaluations so far (and not only our internal evaluations), mOTUs has higher accuracy and recall compared to other k-mer based tools (like kraken, Centrifuge, etc.); but this is true if there are enough reads. You can try to use kraken for your analyses, you will find more species, but there will be many more false positives as well.

Ah, right. I did indeed find it strange that the relative abundance information coming out of mOTU did seem to sort of make sense. However, it was only the counts that I found were too low. But I get now that the amount of total reads play a significant role in these results. I will then also give Kraken a try and compare the relative abundances. Chances are that the mOTU relative abundance table would still be useful and comparable to Kraken (maybe not for the rare species, but at least for the more dominant/common species in a sample). 

Thanks for the feedback and updating the FAQs Wiki page. Really helpful information!

**Comment by AlessioMilanese** [comment]
Maybe adding to the discussion of k-mer based versus marker-gene based profiling approaches, you might be interested in:
https://www.biorxiv.org/content/10.1101/2020.11.14.382994v1.full

**Comment by makrez** [comment]
Hi Alessio

Your explanations are very reasonable concerning this issue and thank you for also adding this to the FAQs. However, I would be interested in your opinion about this case: I have between 70-100 million paired-end reads (total 140-200 million reads) and the absolute number of mapped reads is between 700 - 1500 (including the not assigned reads). The data is from the rhizosphere and since you were asking above about soil samples, I was wondering how you would explain this low mapping rate?

Interestingly, when using kraken2, I get an awful lot of unassigned reads (around 85%).

**Comment by AlessioMilanese** [comment]
Hi @makrez,

> I have between 70-100 million paired-end reads (total 140-200 million reads) and the absolute number of mapped reads is between 700 - 1500 (including the not assigned reads). The data is from the rhizosphere and since you were asking above about soil samples, I was wondering how you would explain this low mapping rate?

We know that soil has really few reads that map to reference genomes (see example: https://www.biorxiv.org/content/10.1101/2021.04.20.440600v1 , figure 1). Since we map to marker genes, only few reads will map because we do not have genomes (and marker genes) in our database that cover these reads.

Solution:
- if you have mOTUs 2.5.1; you can update to mOTUs 2.6.1 where we have many new MAGs from soil (and they should cover some of the unknown species in your samples)
- more involved solution: build MAGs from your samples (they seems quite deeply sequenced, so you can have good results) and add the MAGs to the mOTUs database (there is a set of scripts for doing this). See end of page: https://motu-tool.org/installation.html

> Interestingly, when using kraken2, I get an awful lot of unassigned reads (around 85%).

Kraken is not doing taxonomic profiling directly. It's assigning a taxonomy to each read, and from this you can get a taxonomy. But there are problems related to this (see also figure 1 in https://www.nature.com/articles/s41592-021-01141-3)

**Comment by makrez** [comment]
Hi @AlessioMilanese 

I just realized that I haven't answered you.  Thanks for your opinion on this. It is indeed a problem with missing data in the database. This was confirmed by using other tools as well.

**Comment by AlessioMilanese** [comment]
For your information, now we have also a new version: mOTUs 3.0.
https://bioconda.github.io/recipes/motus/README.html
