### ISSUE TITLE
problem installing mOTU

### ISSUE THREAD

**Issue by Jigyasa3** [motu-tool/mOTUs#74]
Hey @AlessioMilanese!

I am trying to install the mOTU and I am getting the following error-

Code-
```
git clone https://github.com/motu-tool/mOTUs_v2.git
module load python/3.7.3
module load bwa.gcc/0.7.10
module load samtools/1.9
cd mOTU_v2/
python3 setup.py
```

Error-
- Run motus (-v 1, only error messages):
Error: fail to load the script: /home/j/jigyasa-arora/local/mOTUs_v2/bin/append.py
Download the motus profiler again

I re-installed in twice, but getting the same error

**Comment by AlessioMilanese** [comment]
Hi @Jigyasa3 ,

Can you try:
```
module load python/3.7.3
module load bwa.gcc/0.7.10
module load samtools/1.9
which python
which python3

git clone https://github.com/motu-tool/mOTUs.git
cd mOTUs
python3 setup.py
```
We changed the name of the repository (from `mOTUs_v2` to `mOTUs`), maybe that is creating the problem/confusion.
You have to do `cd mOTUs` instead of `cd mOTU_v2/`.

Also, in `cd mOTU_v2/` it might be that it's a wrong directory (because there is a `s` missing in `mOTUs`)?

Let me know if you manage to solve it!
Cheers,
alessio

**Comment by Jigyasa3** [comment]
Hey @AlessioMilanese!

Thank you for a quick reply! I think I managed to solve it by using the conda environment in the `env/` folder.

 Thank you!

**Comment by AlessioMilanese** [comment]
ok nice. I'm closing the issue.
